/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-container": "#e5eeff",
              "inverse-surface": "#213145",
              "secondary-container": "#a7c4fe",
              "on-primary-container": "#7c93cb",
              "on-surface-variant": "#44464f",
              "on-tertiary-container": "#c8835a",
              "surface": "#f8f9ff",
              "primary-container": "#0f2a5c",
              "surface-tint": "#475d92",
              "surface-container-high": "#dce9ff",
              "secondary-fixed": "#d7e2ff",
              "primary": "#00153d",
              "surface-dim": "#cbdbf5",
              "on-secondary-fixed": "#001b3f",
              "on-secondary-fixed-variant": "#284678",
              "on-error": "#ffffff",
              "background": "#f8f9ff",
              "tertiary": "#2c0f00",
              "surface-container-low": "#eff4ff",
              "outline-variant": "#c5c6d1",
              "on-tertiary-fixed": "#321200",
              "tertiary-container": "#4c1f00",
              "secondary-fixed-dim": "#abc7ff",
              "on-primary": "#ffffff",
              "outline": "#757780",
              "on-tertiary-fixed-variant": "#6d3916",
              "on-secondary-container": "#335083",
              "tertiary-fixed-dim": "#ffb68c",
              "surface-container-highest": "#d3e4fe",
              "surface-variant": "#d3e4fe",
              "on-secondary": "#ffffff",
              "on-tertiary": "#ffffff",
              "inverse-on-surface": "#eaf1ff",
              "surface-bright": "#f8f9ff",
              "inverse-primary": "#b0c6ff",
              "on-background": "#0b1c30",
              "primary-fixed": "#d9e2ff",
              "secondary": "#415e91",
              "on-error-container": "#93000a",
              "primary-fixed-dim": "#b0c6ff",
              "surface-container-lowest": "#ffffff",
              "on-surface": "#0b1c30",
              "on-primary-fixed-variant": "#2e4578",
              "tertiary-fixed": "#ffdbc9",
              "on-primary-fixed": "#001945",
              "error-container": "#ffdad6",
              "error": "#ba1a1a"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "xs": "4px",
              "xl": "32px",
              "md": "16px",
              "gutter": "16px",
              "sm": "8px",
              "max-width": "1440px",
              "margin-desktop": "32px",
              "base": "4px",
              "lg": "24px",
              "margin-mobile": "16px"
      },
      "fontFamily": {
              "display-lg": ["Inter"],
              "headline-md": ["Inter"],
              "label-md": ["Inter"],
              "title-md": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "title-lg": ["Inter"],
              "body-lg": ["Inter"],
              "code-md": ["Inter"],
              "headline-lg": ["Inter"],
              "body-md": ["Inter"]
      },
    },
  },
  plugins: [],
}
